kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
  - name: build-test
    image: node:lts-alpine
    commands:
      - yarn
      - CI=true yarn build

  - name: upload
    image: plugins/s3-sync
    settings:
      bucket: nginx
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: dist/
      target: /geo.cgnat.net/
      delete: true
      path_style: true
      endpoint: https://minio.rwx.ovh
    when:
      event: tag

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_server
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
      script:
        - sh /home/jomp16/update_geoip.sh
    when:
      event: tag

trigger:
  event:
    - push
    - tag